### ISSUE TITLE
specify what happens when 2 monolith nodes have the same room loaded

### ISSUE THREAD

**Issue by dyc3** [dyc3/ssw345-group-assignments#20]
Ideas:
- Have the balancers unload all the rooms that were not loaded first
   - this means rooms would need to have a "loaded at" timestamp
   - or, store atomic int in redis, increment the number when a room is loaded, and use that number to determine which room loaded first

**Comment by evanciok** [comment]
@dyc3 also this one if you have a specific spot you'd like it
